version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
