# -- Project identity ---------------------------------------------------------
akki.group=io.akki
akki.maven.group=io.github.octofleet
akki.version=0.2.0-SNAPSHOT
#akki.plugin.id=io.akki
akki.plugin.id=io.github.octofleet.akki

# -- Gradle runtime -----------------------------------------------------------
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.warning.mode=all

# -- Gradle performance -------------------------------------------------------
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

# -- Kotlin ------------------------------------------------------------------
kotlin.code.style=official
akki.kotlin.tested=2.4.0,2.4.10,2.4.20
