name: Build

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: ./gradlew build --continue --stacktrace
      - run: ./gradlew :koverHtmlReport --stacktrace
      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: build/reports/kover/html

      - name: Upload test reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: test-reports
          path: '**/build/reports/tests'

      - name: Report test results
        uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
          annotate_only: ${{ github.event.pull_request.head.repo.fork == true }}

  lincheck:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
        with:
          cache: false
      - run: ./gradlew lincheck --max-workers=1 --stacktrace
      - name: Upload test reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: lincheck-reports
          path: '**/build/reports/tests'
