name: Build

on:
  pull_request: {}
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build --continue --stacktrace
      - run: ./gradlew koverHtmlReport
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: build/reports/kover/html

      - uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
